apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-kubectl
rules:
  - apiGroups: [""]
    resources:
      - deployments
      - configmaps
      - services
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
