apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: jenkins-kubectl
roleRef:
  kind: Role
  name: jenkins-kubectl
  apiGroup: rbac.authorization.k8s.io
