apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-kubectl
  namespace: default
subjects:
  - kind: ServiceAccount
    name: jenkins-kubectl
    namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-kubectl
  apiGroup: rbac.authorization.k8s.io
